export const WATCHES = [
  {
    id: 'foret-perpetuelle',
    name: 'Forêt Perpetuelle',
    collection: 'Masterpiece',
    tagline: 'The harmony of nature and time.',
    category: 'perpetual',
    price: 98500,
    limited: true,
    limitedPieces: 88,
    description: 'A grand complication of singular ambition. The Forêt Perpetuelle unites a self-correcting perpetual calendar with a moonphase accurate to one day in 122 years — a technical achievement realised through an entirely proprietary gear train engineered over eleven years at the Geneva atelier.',
    craftsmanship: 'Each case requires forty-seven hours of hand-finishing alone. Chamfered bridges are polished using a 2mm boxwood buff at angles maintained to within half a degree. Perlage is applied across every visible plate surface — 2,847 circles per movement, each overlapping by precisely one-third.',
    materials: 'Case and lugs formed from a proprietary 18-karat champagne gold alloy, alloyed in-house with platinum for hardness retention. The deep forest-green grand feu enamel dial is fired at 840°C over a pure copper base, with three successive layerings for depth and translucency.',
    movement: 'Manufacture calibre V.24-001, hand-wound, with twin mainspring barrels providing sequential power delivery. The column-wheel perpetual calendar mechanism distinguishes leap years using a 48-month cam of proprietary design.',
    specs: {
      caliber: 'V.24-001 Manufacture, Manual Wind',
      complication: 'Perpetual Calendar, Moonphase, Power Reserve',
      powerReserve: '72 Hours, Twin Barrel',
      caseMaterial: '18k Champagne Gold (Proprietary Alloy)',
      caseSize: '40mm diameter',
      caseThickness: '11.4mm',
      crystal: 'Domed Sapphire, Triple AR-Coated',
      waterResistance: '50 metres / 5 ATM',
      weight: '185g with bracelet',
      movement: 'Manufacture V.24-001, 6Hz',
      jewels: '37 jewels',
      frequency: '21,600 vph',
      finishing: 'Geneva Seal, COSC Certified',
    },
    images: ['/images/watch1.png'],
    altImages: ['/images/watch3.png', '/images/watch5.png', '/images/watch6.png'],
    reviews: [
      { name: 'A. Belmont', location: 'Geneva', date: 'October 2024', stars: 5, text: 'An absolute triumph. The finishing on the movement rivals anything from the Holy Trinity. The perpetual calendar mechanism is an education in miniature engineering.' },
      { name: 'J. Harrison', location: 'London', date: 'August 2024', stars: 5, text: 'Purchased at the Geneva boutique after a private viewing. The dial under natural light has a depth I have never encountered before on any piece in my collection.' },
      { name: 'M. Dubois', location: 'Paris', date: 'May 2024', stars: 5, text: 'My third VERDE piece. They continue to exceed themselves in both craft and in the quality of client attention. The director spent four hours with me — unhurried, encyclopaedic.' },
    ],
  },
  {
    id: 'noir-classique',
    name: 'Noir Classique',
    collection: 'Dress',
    tagline: 'The depth of obsidian.',
    category: 'dress',
    price: 42000,
    description: 'An argument for restraint. The Noir Classique demonstrates that the highest expression of watchmaking is knowing precisely what to leave out. An obsidian-black grand feu enamel dial, no date, no complication beyond hours and minutes, and a movement of breathtaking simplicity at its most refined.',
    craftsmanship: 'The case profile is machined in a single operation from a solid block of 18-karat white gold, then hand-polished across eleven distinct surfaces over thirty-six hours. The crown is set flush with the case band — an invisible detail that defines the whole silhouette.',
    materials: 'Case in 18-karat polished white gold. The obsidian dial is fired over copper using the grand feu enamel technique — requiring six separate firings. Applied hour markers are solid white gold, bevelled and set by hand. Double anti-reflective coating on sapphire crystal for optical clarity at all angles.',
    movement: 'Calibre V.12-003 automatic, with a centrally mounted rotor in 22-karat gold. The movement is hand-decorated with Cotes de Geneve finishing throughout, visible through the full exhibition caseback in sapphire crystal.',
    specs: {
      caliber: 'V.12-003 Automatic',
      complication: 'Hours, Minutes, Small Seconds',
      powerReserve: '48 Hours',
      caseMaterial: '18k White Gold, Polished',
      caseSize: '38mm diameter',
      caseThickness: '8.2mm',
      crystal: 'Sapphire, Double AR-Coated',
      waterResistance: '30 metres / 3 ATM',
      weight: '145g',
      movement: 'Manufacture V.12-003, In-house',
      jewels: '28 jewels',
      frequency: '28,800 vph',
      finishing: 'Cotes de Geneve, Perlage, Bevelled Bridges',
    },
    images: ['/images/watch2.png'],
    altImages: ['/images/watch4.png', '/images/watch1.png', '/images/watch6.png'],
    reviews: [
      { name: 'C. Worthington', location: 'New York', date: 'September 2024', stars: 5, text: 'The most elegant dress watch I have owned in thirty years of collecting. The dial has a depth that photographs cannot capture.' },
      { name: 'H. Yamamoto', location: 'Tokyo', date: 'July 2024', stars: 5, text: 'Perfection in its simplicity. The case finishing is extraordinary under a loupe.' },
    ],
  },
  {
    id: 'alpine-sport',
    name: 'Alpine Sport',
    collection: 'Sport',
    tagline: 'Precision for the altitude.',
    category: 'sport',
    price: 35000,
    description: 'Born from a brief but inviolable conviction: that a sports watch should be as precise at 4,000 metres as on the trading floor. The Alpine Sport is built to the most demanding standards, with technical solutions borrowed from aerospace and finished with the hand of a traditional atelier.',
    craftsmanship: 'The Grade 5 titanium case is machined across seven axes, then surface-treated with a proprietary brushing technique that creates a fine grain invisible to the naked eye but detectable under a loupe. The integrated bracelet is polished only on its outer edges.',
    materials: 'Grade 5 aerospace titanium for case and bracelet, selected for its ratio of strength to lightness — identical to the material used in the turbine blades of commercial aircraft. The black ceramic bezel is formed under 8,000 tonnes of isostatic pressure and hand-polished after firing.',
    movement: 'Calibre V.35-007 automatic with integrated chronograph function using a proprietary column-wheel mechanism and vertical clutch for instantaneous start without jump. The rotor bears the VERDE monogram, engraved by hand.',
    specs: {
      caliber: 'V.35-007 Automatic Chronograph',
      complication: 'Flyback Chronograph, 200m Water Resistance',
      powerReserve: '60 Hours',
      caseMaterial: 'Grade 5 Titanium, Brushed',
      caseSize: '42mm diameter',
      caseThickness: '13.1mm',
      crystal: 'Flat Sapphire, Scratch-Resistant',
      waterResistance: '200 metres / 20 ATM',
      weight: '120g without bracelet',
      movement: 'Manufacture V.35-007, Column-Wheel',
      jewels: '35 jewels',
      frequency: '36,000 vph',
      finishing: 'Alternate Brushed / Polished, COSC Certified',
    },
    images: ['/images/watch3.png'],
    altImages: ['/images/watch1.png', '/images/watch5.png', '/images/watch2.png'],
    reviews: [
      { name: 'D. Okonkwo', location: 'Dubai', date: 'November 2024', stars: 5, text: 'Wore this on an ascent of Mont Blanc. Kept perfect time throughout. Remarkable that something this technical can be this beautiful.' },
      { name: 'P. Svensson', location: 'Singapore', date: 'June 2024', stars: 5, text: 'The integrated bracelet is an engineering masterpiece. Sits on the wrist as though it were made for no other purpose.' },
    ],
  },
  {
    id: 'edition-1887',
    name: 'Edition 1887',
    collection: 'Heritage',
    tagline: 'A tribute to our origins.',
    category: 'dress',
    price: 67000,
    description: 'A modern watch with the soul of the first. The Edition 1887 is a precise reimagining of Antoine Verde\'s original pocket watch design — adapted for the wrist, engineered for the century, and decorated with techniques that have not changed since he first used them in his Geneva workshop.',
    craftsmanship: 'The case band features hand-engraved floral scrollwork applied by a single artisan over sixty hours per piece. No engraving is mechanically duplicated — each flower, each tendril, each leaf is unique. The hands are cut from solid rose gold and polished under 40x magnification.',
    materials: 'Case in 18-karat rose gold with a softly domed profile referencing Antoine Verde\'s original pocket watch. The dial is a champagne guilloche executed on a 19th-century rose engine, a machine VERDE maintains and operates exclusively for this reference. The calfskin strap is hand-stitched in Geneva.',
    movement: 'Calibre V.18-001 manual wind, with five-day power reserve delivered from a single mainspring barrel of exceptional length. The movement bridges are decorated with cotes de Geneve in a starburst pattern echoing the founder\'s original signature decoration.',
    specs: {
      caliber: 'V.18-001 Manual Wind',
      complication: 'Hours, Minutes, Power Reserve Indicator',
      powerReserve: '5 Days (120 Hours)',
      caseMaterial: '18k Rose Gold, Hand-Engraved',
      caseSize: '39mm diameter',
      caseThickness: '9.8mm',
      crystal: 'Domed Sapphire, AR-Coated',
      waterResistance: '30 metres / 3 ATM',
      weight: '160g',
      movement: 'Manufacture V.18-001, Single Barrel',
      jewels: '21 jewels',
      frequency: '18,000 vph',
      finishing: 'Starburst Cotes de Geneve, Hand-Bevelled',
    },
    images: ['/images/watch4.png'],
    altImages: ['/images/watch2.png', '/images/watch1.png', '/images/watch5.png'],
    reviews: [
      { name: 'F. Marchetti', location: 'Milan', date: 'October 2024', stars: 5, text: 'The guilloche dial is extraordinary. You can spend an hour discovering its details. A timepiece of remarkable depth.' },
    ],
  },
  {
    id: 'champagne-dress',
    name: 'Champagne Dress',
    collection: 'Celebration',
    tagline: 'Celebration in every second.',
    category: 'dress',
    price: 55000,
    description: 'Ultra-thin. Champagne-coloured. Diamond-set. The watch for moments that exceed all measurement. The Champagne Dress was designed for those who regard a wristwatch not as a tool of timekeeping but as the final detail on which everything depends.',
    craftsmanship: 'At 6.2 millimetres, the case required the development of an entirely new casing technique. Every component is thinner than anything previously attempted. The diamond-set bezel features 62 brilliant-cut stones, each selected for cut and colour consistency, set individually with a hand-held graver.',
    materials: 'Case in 18-karat yellow gold with ultra-thin profile. The champagne dial is crafted from precious metal — a solid gold base with a fine sunburst finish applied by hand. The bezel is set with 62 brilliant-cut diamonds totalling 1.4 carats, each F-G colour, VS clarity.',
    movement: 'Ultra-thin calibre V.08-002 automatic, at 2.8mm our thinnest manufacture movement. The micro-rotor in 22-karat gold winds through a peripheral system, eliminating the central rotor that would otherwise add height.',
    specs: {
      caliber: 'V.08-002 Ultra-Thin Automatic',
      complication: 'Hours, Minutes, Date',
      powerReserve: '42 Hours',
      caseMaterial: '18k Yellow Gold, Diamond-Set Bezel',
      caseSize: '36mm diameter',
      caseThickness: '6.2mm',
      crystal: 'Sapphire, Ultra-Flat Profile',
      waterResistance: '30 metres / 3 ATM',
      weight: '155g',
      movement: 'Manufacture V.08-002, Micro-Rotor',
      jewels: '24 jewels + 62 diamonds (1.4ct)',
      frequency: '28,800 vph',
      finishing: 'Mirror-Polished Gold, Diamond-Set Bezel',
    },
    images: ['/images/watch5.png'],
    altImages: ['/images/watch2.png', '/images/watch4.png', '/images/watch1.png'],
    reviews: [
      { name: 'A. de Villiers', location: 'Geneva', date: 'December 2024', stars: 5, text: 'Purchased as an anniversary gift. The director had it ready in a cedar box with a handwritten note. An experience as refined as the watch itself.' },
    ],
  },
  {
    id: 'bespoke-atelier',
    name: 'Bespoke Atelier',
    collection: 'Custom',
    tagline: 'Made for one person only.',
    category: 'bespoke',
    price: 145000,
    description: 'There is no reference number, no production run, no second example. A VERDE Bespoke commission is a single object, made once, for one person — a collaboration between the client and our atelier that unfolds over twelve to eighteen months of conversation, design, revision, and craft.',
    craftsmanship: 'Every commissioned piece passes through the hands of at least twelve specialists — from the case engraver to the dial enamellist to the master watchmaker who assembles the final movement. The commissioner\'s name is engraved inside the caseback, alongside the reference date and the signature of the responsible master.',
    materials: 'All materials are selected by the client in consultation with our materials director. The atelier maintains an archive of exceptional materials including meteorite slices, precious wood dials, hand-painted miniature portraits, and a collection of historic enamel shards that can be incorporated into dial compositions.',
    movement: 'Movement specifications are defined per commission. Clients may select from six manufacture calibres, or commission a movement modification for additional complications. All Bespoke movements receive full Geneva Seal finishing.',
    specs: {
      caliber: 'Client-specified manufacture calibre',
      complication: 'As commissioned',
      powerReserve: 'Variable by calibre selection',
      caseMaterial: "Client's choice of 18k gold or platinum",
      caseSize: 'Custom, from 36mm to 44mm',
      caseThickness: 'Variable',
      crystal: 'Sapphire, profile to be determined',
      waterResistance: 'Variable by design',
      weight: 'To be determined',
      movement: 'From manufacture range, modified to brief',
      jewels: 'Variable by complication',
      frequency: '18,000 to 36,000 vph',
      finishing: 'Full Geneva Seal, per client brief',
    },
    images: ['/images/watch6.png'],
    altImages: ['/images/watch1.png', '/images/watch4.png', '/images/watch3.png'],
    reviews: [
      { name: 'R. Nakamura', location: 'Tokyo', date: 'March 2024', stars: 5, text: 'Eighteen months from first conversation to delivery. The result exceeded what I believed possible. An experience — and a watch — I will carry for the rest of my life.' },
    ],
  },
];

export const formatPrice = (price: number, currency: string, rate: number) =>
  new Intl.NumberFormat('en-CH', { style: 'currency', currency, maximumFractionDigits: 0 }).format(price * rate);

export const CURRENCY_RATES = { CHF: 1, USD: 1.12, GBP: 0.89, EUR: 1.05, AED: 4.11, JPY: 162 };

export const BOUTIQUES = [
  { id: 'geneva', city: 'Geneva (HQ)', country: 'Switzerland', address: 'Rue de la Paix 14, 1211 Geneva', phone: '+41 22 000 1234', hours: 'Mon-Fri: 10:00-18:00 · Sat: 10:00-16:00', region: 'europe', mapPin: { x: 52, y: 42 }, director: 'Pierre Laurent', directorTitle: 'Maison Director', directorImage: '/images/director-pierre.png' },
  { id: 'paris', city: 'Paris', country: 'France', address: 'Place Vendome 8, 75001 Paris', phone: '+33 1 00 00 00 00', hours: 'Mon-Sat: 11:00-19:00', region: 'europe', mapPin: { x: 51, y: 37 }, director: 'Sophie Renard', directorTitle: 'Collections Director', directorImage: '/images/director-sophie.png' },
  { id: 'london', city: 'London', country: 'United Kingdom', address: 'New Bond Street 144, London W1S 2PF', phone: '+44 20 0000 0000', hours: 'Mon-Sat: 10:00-18:00', region: 'europe', mapPin: { x: 49, y: 35 }, director: 'James Whitmore', directorTitle: 'Atelier Director', directorImage: '/images/director-james.png' },
  { id: 'milan', city: 'Milan', country: 'Italy', address: 'Via Montenapoleone 12, 20121 Milan', phone: '+39 02 0000 0000', hours: 'Mon-Sat: 10:00-19:00', region: 'europe', mapPin: { x: 53, y: 40 }, director: 'Giulia Ferretti', directorTitle: 'Style Director', directorImage: '/images/director-giulia.png' },
  { id: 'new-york', city: 'New York', country: 'USA', address: '745 Fifth Avenue, New York NY 10022', phone: '+1 212 000 0000', hours: 'Mon-Sat: 10:00-18:00', region: 'americas', mapPin: { x: 29, y: 38 }, director: 'Claire Ashford', directorTitle: 'Americas Director', directorImage: '/images/director-claire.png' },
  { id: 'dubai', city: 'Dubai', country: 'UAE', address: 'Dubai Mall, Level 2, Financial Centre Road', phone: '+971 4 000 0000', hours: 'Daily: 10:00-22:00', region: 'middle-east', mapPin: { x: 60, y: 46 }, director: 'Omar Al-Rashid', directorTitle: 'Middle East Director', directorImage: '/images/director-omar.png' },
  { id: 'tokyo', city: 'Tokyo', country: 'Japan', address: 'Ginza 5-chome 10, Chuo-ku, Tokyo', phone: '+81 3 0000 0000', hours: 'Daily: 11:00-20:00', region: 'asia', mapPin: { x: 73, y: 40 }, director: 'Yuki Tanaka', directorTitle: 'Asia Director', directorImage: '/images/director-yuki.png' },
  { id: 'singapore', city: 'Singapore', country: 'Singapore', address: 'Marina Bay Sands, Tower 2, Bayfront Avenue', phone: '+65 6000 0000', hours: 'Daily: 10:00-21:00', region: 'asia', mapPin: { x: 68, y: 52 }, director: 'Wei Lin', directorTitle: 'Southeast Asia Director', directorImage: '/images/director-wei.png' },
];
